# Part 1: Get Pictures

In [1]:
import os
import tensorflow as tf
import cv2
import matplotlib.pyplot as plt
import numpy as np

2023-03-18 19:57:47.708573: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/ros/noetic/lib
2023-03-18 19:57:47.708601: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
FILEPATH = '../assets/images/outer_lap/'
print(len(os.listdir(FILEPATH)), 'images')


204 images


In [3]:
frame0 = os.listdir('../assets/images/outer_lap/')[0]
print('first image:', frame0)

first image: [0.5, 0.0]2023-03-18 19:33:27.227074.png


In [4]:
vels = frame0.split(']')[0].split('[')[1].split(',')
vels

['0.5', ' 0.0']

# Part 2: Get labels from filename

In [5]:
def get_vels_from_filename(filename: str):
    return filename.split(']')[0].split('[')[1].split(',')


def get_action_from_vels(vels: list):
    linear_vel, angular_vel = [float(v) for v in vels]
    if angular_vel == 0: # forward
        action = 0 
    else:
        if angular_vel > 0: 
            action = 1 # left
        else: action = 2 # right
    return action

In [6]:
get_action_from_vels(get_vels_from_filename(frame0))


0

In [7]:
for im in os.listdir('../assets/images/outer_lap/'):
    print('----')
    print(im)
    a = get_action_from_vels(get_vels_from_filename(im))
    print(a)
    print(tf.one_hot(a, 3))

----
[0.5, 0.0]2023-03-18 19:33:27.227074.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:29.765992.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:39.134931.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:32.988132.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:25.753395.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:39.403489.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.0, 0.0]2023-03-18 19:33:41.011174.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:29.365980.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:33.386590.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:33:18.676281.png
0
tf.Tensor([1. 0. 0.], shape=(3,), dtype=float32)
----
[0.5, 0.0]2023-03-18 19:3

2023-03-18 19:57:55.734058: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2023-03-18 19:57:55.734541: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/fizzer/.local/lib/python3.8/site-packages/cv2/../../lib64:/opt/ros/noetic/lib
2023-03-18 19:57:55.734611: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/fizzer/.local/lib/python3.8/site-packages/cv2/../../lib64:/opt/ros/noetic/lib
2023-03-18 19:57:55.734660: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic libra

In [8]:
image = cv2.imread(FILEPATH + '/' + frame0, )
image.shape
IMAGE_SHAPE = image.shape
IMAGE_SHAPE

(180, 320, 3)

In [9]:
# cv2.imshow('image', image)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# type a key to close image window

# Part 3: Image Processing

In [10]:
IMGPATH = '../assets/images/outer_lap/[0.5, 0.0]2023-03-18 19:33:37.789559.png'
grass_img = cv2.imread(IMGPATH)
cv2.imshow('grass', grass_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
# === show individual channels of HSV
cv2.imshow('h', grass_hsv[:,:,0])
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('s', grass_hsv[:,:,1])
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imshow('v', grass_hsv[:,:,2])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
# === Show hsv in channel order (R,G,B) => (H,S,V)
# note: had to reverse channel order since cv2 works with GBR
grass_hsv = cv2.cvtColor(grass_img, cv2.COLOR_BGR2HSV)
cv2.imshow('h,s,v', grass_hsv[:,:,::-1])
cv2.waitKey(0)
cv2.destroyAllWindows()

In [33]:
# === Dark grass image to tune HSV thresholds
IMGPATH = '../assets/images/outer_lap/[0.0, 1.0]2023-03-18 19:33:33.120816.png'
grass_hsv = cv2.cvtColor(grass_img, cv2.COLOR_BGR2HSV)
grass_img = cv2.imread(IMGPATH)
grass_min = np.asarray([0,40,0])
grass_max = np.asarray([255,60,255])
grass_mask = grass_hsv[:,:,0].copy()
grass_mask = cv2.inRange(grass_img, grass_min, grass_max, grass_mask)
cv2.imshow('mask grass road', grass_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
IMGPATH = '../assets/images/outer_lap/[0.5, 0.0]2023-03-18 19:33:37.789559.png'
grass_hsv = cv2.cvtColor(grass_img, cv2.COLOR_BGR2HSV)
grass_img = cv2.imread(IMGPATH)
grass_min = np.asarray([0,0,180])
grass_max = np.asarray([255,255, 255])
grass_mask = grass_hsv[:,:,0].copy()
grass_mask = cv2.inRange(grass_img, grass_min, grass_max, grass_mask)
cv2.imshow('mask grass road', grass_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
IMGPATH = '../assets/images/outer_lap/[0.5, 0.0]2023-03-18 19:33:37.789559.png'
grass_hsv = cv2.cvtColor(grass_img, cv2.COLOR_BGR2HSV)
grass_img = cv2.imread(IMGPATH)
grass_min = np.asarray([0,0,180])
grass_max = np.asarray([255,255, 255])
grass_mask = grass_hsv[:,:,0].copy()
grass_mask = cv2.inRange(grass_img, grass_min, grass_max, grass_mask)
cv2.imshow('mask grass road', grass_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
IMGPATH = '../assets/images/outer_lap/[0.5, 0.0]2023-03-18 19:33:35.509613.png'
grass_hsv = cv2.cvtColor(grass_img, cv2.COLOR_BGR2HSV)
grass_img = cv2.imread(IMGPATH)
grass_min = np.asarray([0,0,180])
grass_max = np.asarray([255,255, 255])
grass_mask = grass_hsv[:,:,0].copy()
grass_mask = cv2.inRange(grass_img, grass_min, grass_max, grass_mask)
cv2.imshow('mask grass road', grass_mask)
cv2.waitKey(0)
cv2.destroyAllWindows()